### ISSUE TITLE
Error running call

### ISSUE THREAD

**Issue by vschulz** [ciceklab/ECOLE#2]
ECOLE calling does not run for me, it gives an error
source ecole_call.sh
Creation of the directory failed
[ 2024-06-28 11:01:20 ]  ECOLÉ:  Using GPU!
[ 2024-06-28 11:01:22 ]  ECOLÉ:  Calling for CNV regions...
  0%|                                                                                     | 0/28 [00:00<?, ?it/s][ 2024-06-28 11:01:22 ]  ECOLÉ:  calling sample: P1_44
/home/pgal/.local/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
  0%|                                                                                     | 0/28 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "./scripts/ECOLE_call.py", line 321, in <module>
    readdepths_data = sequence.pad_sequences(readdepths_data, maxlen=1005,dtype=np.float32,value=-1)
  File "/home/pgal/anaconda3/envs/ecole_env/lib/python3.8/site-packages/tensorflow/python/keras/preprocessing/sequence.py", line 156, in pad_sequences
    return sequence.pad_sequences(
  File "/home/pgal/anaconda3/envs/ecole_env/lib/python3.8/site-packages/keras_preprocessing/sequence.py", line 96, in pad_sequences
    trunc = np.asarray(trunc, dtype=dtype)
  File "/home/pgal/.local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'X'

**Comment by alperylmzz** [comment]
The model expects a 'chr' prefix for chromosome information, such as 'chrX' instead of 'X'. This might be causing the problem. Please check your read depth file.
